### ISSUE TITLE
go-feature-flag-in-process is not in the package

### ISSUE THREAD

**Issue by zaitera** [open-feature/go-sdk-contrib#570]
updated to the latest 0.2.0 but did not want to change my existing usage of the lib, so I wanted to switch to "in-process" part that uses go feature flag under the hood.
I cannot use that provider.
![image](https://github.com/user-attachments/assets/a914723a-36d7-4ef3-8f7e-13c579fc4f67)
![image](https://github.com/user-attachments/assets/f0615479-d305-4cd7-ae55-d5208983dd80)

**Comment by thomaspoignant** [comment]
Thanks for raising this issue, let me check and I get back to you.

**Comment by thomaspoignant** [comment]
@zaitera I've reproduced your issue on my computer and I think the issue was because it is a brand new package and my go installation had some caching issue.

#### What I did do to solve the caching issue?
I have forced the version when doing the 1st `go get` command.
```
go get github.com/open-feature/go-sdk-contrib/providers/go-feature-flag-in-process@v0.1.0
```
This has solved the problem and download the module.

#### Will it work for others?
To be sure it was a caching issue, I also installed a fresh Ubuntu with a brand new go environment.
When doing the `go get github.com/open-feature/go-sdk-contrib/providers/go-feature-flag-in-process` it has worked without specifying any version.


Can you tell me if it has worked for you too?
If so don't hesitate to close the issue.

**Comment by zaitera** [comment]
@thomaspoignant thanks for the quick response, that worked fine!

**Comment by thomaspoignant** [comment]
I am glad it worked for you 🎉 
Thanks for raising it !

**Comment by zaitera** [comment]
@thomaspoignant just a quick question, what is the reason behind calling it in process?
is it something we need to treat carefully and not take to production? 
because it seems to me it is just the same code that used to be on normal go-feature-flag before that latest update to 0.2.0

**Comment by thomaspoignant** [comment]
@zaitera it is called `in-process` because the evaluation is made directly in the provider and is not doing any remote call to the `relay-proxy`.
It is not a reference to the state of the provider, it is production-ready.

**Comment by zaitera** [comment]
clear, thanks for the quick responses :)
